### ISSUE TITLE
line spacing

### ISSUE THREAD

**Issue by y1my1** [nraboy/hugo-phlat-theme#12]
Hi, 

Thanks for creating this theme. I am trying to build a blog in Chinese. It looks pretty good except line spacing is too small. Can I please point out where should I go if I want to increase the line spacing?

**Comment by nraboy** [comment]
The theme uses Bootstrap. You might try altering the line spacing here:

https://github.com/nraboy/hugo-phlat-theme/blob/master/static/css/phlat.css

Best,
