### ISSUE TITLE
Creating New site with the theme

### ISSUE THREAD

**Issue by luisevd** [nraboy/hugo-phlat-theme#3]
I was following your instructions about creating a new site, however there are a few things missing in the Readme.md.

1) Steps to Create the pages about and contact using 
`hugo new page/about.md`

2)For the first post must include at least 1 categories because hugo will have an error serving:

`template: theme/_default/single.content.html:5:54: executing "theme/_default/single.content.html" at <len>: wrong number of args for len: want 1 got 0 in theme/_default/single.content.html` 

The number two I think could be considered as a bug.

By the way your template is awesome, amazing job!

**Comment by nraboy** [comment]
First off, thank you for the compliment about my theme!

In regards to your concerns:
1. Should I add this step?  I figured it was a pretty standard Hugo 101 term not specific to my theme, but I'm always looking for other perspectives.  If you think it would benefit, I can certainly add it.
2. That does sound like a bug.  I'll get on it!

Best,

**Comment by luisevd** [comment]
From README.md:

> This theme expects the standard Hugo site layout.

If the about and contact page are required for the first run, I think it is necessary to add it. 

I was getting the categories error and I thought it was related to the about and contact pages until I read the code, think about the newbies problems to create the new page since the QuickStart guide from hugo it does not include the command, however it encourages you to find a better theme and to try it.

**Comment by JohnBlood** [comment]
Hi,

I'm a noob getting the same problem as above. All I did was create new page with  `hugo new post/welcome.md`. When I made draft false, I got the error. What's the problem?

Thanks for a great theme

**Comment by nraboy** [comment]
Fixed the category bug in https://github.com/nraboy/hugo-phlat-theme/commit/17c8c93908ea535b443577464db508f43b2ba5db.
